btrfs-progs: tests: output nullb error/warning message to stderr
Outputting these messages to stdout can compromise other functions'
output.  Instead, output them to stderr to keep the results clean.

Reviewed-by: Qu Wenruo <wqu@suse.com>
Signed-off-by: Naohiro Aota <naohiro.aota@wdc.com>
Signed-off-by: David Sterba <dsterba@suse.com>

diff --git a/tests/nullb b/tests/nullb
--- a/tests/nullb
+++ b/tests/nullb
@@ -34,12 +34,12 @@ SYSFS='/sys/kernel/config/nullb'
 # setup
 
 function _error() {
-	echo "ERROR: $@"
+	echo "ERROR: $@" 1>&2
 	exit 1
 }
 
 function _warn() {
-	echo "WARNING: $@"
+	echo "WARNING: $@" 1>&2
 }
 
 function _msg() {
